site_name: fuji-x-weekly-simluation-profiles
repo_url: https://github.com/ntonthat/fuji-x-weekly-simluation-profiles
site_url: https://ntonthat.github.io/fuji-x-weekly-simluation-profiles
site_description: Scrape the www.fujixweekly.com for Fuji X simulation profiles
site_author: Nam Tonthat
edit_uri: edit/main/docs/
repo_name: ntonthat/fuji-x-weekly-simluation-profiles
copyright: Maintained by <a href="https://ntonthat.com">Florian</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append('../')
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ntonthat/fuji-x-weekly-simluation-profiles
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/fuji-x-weekly-simluation-profiles

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
