name: "setup-poetry-env"
description: "Composite action to setup the Python and poetry environment."

inputs:
  python-version:
    required: false
    description: "The python version to use"
    default: "3.13.0"

runs:
  using: "composite"
  steps:
    - name: Set up python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - uses: hynek/setup-cached-uv@v2
      with:
        if-use-cache: ${{ startsWith(matrix.python-version, 'pypy') }}

    - name: Install dependencies
      run: make install
      shell: bash
