name: Main

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  quality:
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: 3.13.0
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Set up the environment
        uses: ./.github/actions/setup-uv-env

      - name: Run checks
        run: make check

  tox:
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: 3.13.0
    strategy:
      matrix:
        python-version: ["${{ env.PYTHON_VERSION }}"]
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: snok/install-uv@v1

      - name: Install tox
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox tox-gh-actions

      # - name: Test with tox
      #   run: tox

      - name: Upload coverage reports to Codecov using Python ${{ matrix.python-version }}
        uses: codecov/codecov-action@v3

  check-docs:
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: 3.13.0
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Set up the environment
        uses: ./.github/actions/setup-uv-env

      - name: Check if documentation can be built
        run: uv run mkdocs build -s
