name: Main

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  quality:
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: 3.13.0
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Set up the environment
        uses: ./.github/actions/setup-uv-env

      - name: Run checks
        run: |
          make install GROUP_NAME=dev
          make check

  tox:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env:
          - "3.13"
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Set up the environment
        uses: ./.github/actions/setup-uv-env

      - name: Install tox packages
        run: make install GROUP_NAME=dev

      # - name: Test with tox
      #   run: tox

      - name: Upload coverage reports to Codecov using Python ${{ matrix.env }}
        uses: codecov/codecov-action@v3

  check-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Set up the environment
        uses: ./.github/actions/setup-uv-env

      - name: Install docs packages
        run: make install GROUP_NAME=docs

      - name: Check if documentation can be built
        run: uv run mkdocs build -s
