name: fortnight-scrape

on:
  schedule: # run every two weeks
    - cron: "0 0 1,15 * *"

jobs:
  fujifilm-scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out
        uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Set up the environment
        uses: ./.github/actions/setup-uv-env

      - name: Scrape fujixweekly.com website
        run: make scrape

      - name: Commit files
        uses: stefanzweifel/git-auto-commit-action@v4
